demo3:
	gcc demo3.c -omain
demo2:
	gcc demo2.c -omain
pipedemo:
	gcc pipe.c -omain
pipe:
	gcc fifoA.c -oA
	gcc fifoB.c -oB
proc:
	gcc procA.c -oA
	gcc procB.c -oB
sigqueue:
	gcc sigqueue.c -omain2
sigaction:
	gcc sigaction.c -omain
sighandle:
	gcc sighandle.c -omain
demo1:
	gcc demo1.c -omain
sigsuspend:
	gcc suspend.c -omain
sigmask:
	gcc sigmask.c -o main
clean:
	rm -rf main
	rm -rf main2
